// Copyright (c) Microsoft. All rights reserved.

package com.microsoft.azure.iot.iothubreact

import java.time.Instant
import java.util

import com.microsoft.azure.eventhubs.EventData
import com.microsoft.azure.servicebus.amqp.AmqpConstants.AMQP_PROPERTY_CONTENT_TYPE

/* MessageFromDevice factory */
private object MessageFromDevice {

  /** Create a user friendly representation of the IoT message from the raw
    * data coming from the storage
    *
    * @param rawData   Raw data retrieved from the IoT hub storage
    * @param partition Storage partition where the message was retrieved from
    *
    * @return
    */
  def apply(rawData: EventData, partition: Option[Int]): MessageFromDevice = {
    new MessageFromDevice(Some(rawData), partition)
  }
}

/** Expose the IoT device message body and timestamp
  *
  * @param partition Storage partition where the message was retrieved from
  */
class MessageFromDevice(data: Option[EventData], val partition: Option[Int]) {

  // NOTE: this will become a system property in future versions of Azure SDKs
  // @todo Use system property once available in Azure SDK
  private[iothubreact] val contentTypeProperty = "$$contentType"

  // NOTE: this will become a system property in future versions of Azure SDKs
  // @todo Use system property once available in Azure SDK
  private[iothubreact] val modelProperty = "$$contentModel"

  // Internal properties set by IoT stoage
  private[this] lazy val systemProps = data.get.getSystemProperties()

  // Meta properties set by the device
  // Note: empty when using MQTT
  lazy val properties: util.Map[String, String] = data.get.getProperties()

  // Whether this is a keep alive message generated by the stream and not by IoT hub
  val isKeepAlive: Boolean = (partition == None)

  // Model name, the class to use to map the payload
  // Note: MQTT not supported yet
  lazy val model: String = properties.getOrDefault(modelProperty, "")

  // Content type, e.g. JSON/Protobuf/Bond etc.
  // Currently a private property until supported in Azure SDKs
  //private[iothubreact] lazy val contentType = data.get.getSystemProperties.get(AMQP_PROPERTY_CONTENT_TYPE)
  // @todo Make public once available in Azure SDK
  private[iothubreact] lazy val contentType = properties.getOrDefault(contentTypeProperty, "")

  /** Time when the message was received by IoT hub service
    * Note that this might differ from the time set by the device, e.g. in case
    * of batch uploads
    */
  lazy val created: Instant = systemProps.getEnqueuedTime

  /** IoT message offset
    * Useful for example to store the current position in the stream
    */
  lazy val offset: String = systemProps.getOffset

  // IoT message sequence number
  lazy val sequenceNumber: Long = systemProps.getSequenceNumber

  // ID of the device who sent the message
  lazy val deviceId: String = systemProps.get("iothub-connection-device-id").toString

  // IoT message content bytes
  lazy val content: Array[Byte] = data.get.getBody

  // IoT message content as string, e.g. JSON/XML/etc.
  lazy val contentAsString: String = new String(content)
}
