// Copyright (c) Microsoft. All rights reserved.

package com.microsoft.azure.iot.iothubreact

import java.time.Instant
import java.util

import com.microsoft.azure.eventhubs.EventData
import com.microsoft.azure.servicebus.amqp.AmqpConstants

/* MessageFromDevice factory */
private object MessageFromDevice {

  /** Create a user friendly representation of the IoT message from the raw
    * data coming from the storage
    *
    * @param rawData   Raw data retrieved from the IoT hub storage
    * @param partition Storage partition where the message was retrieved from
    *
    * @return
    */
  def apply(rawData: EventData, partition: Option[Int]): MessageFromDevice = {
    new MessageFromDevice(Some(rawData), partition)
  }
}

/** Expose the IoT device message body and timestamp
  *
  * @param partition Storage partition where the message was retrieved from
  */
class MessageFromDevice(data: Option[EventData], val partition: Option[Int]) {

  // TODO: verify and document which properties work over which protocol
  // TODO: use system property for Content Type once available in Azure SDK
  // TODO: use system property for Message Type once available in Azure SDK
  // TODO: Are properties missing when using MQTT ?

  // NOTE: this should become a system property in future versions of Azure SDKs
  // contentTypeProperty = AmqpConstants.AMQP_PROPERTY_CONTENT_TYPE
  private[iothubreact] val contentTypeProperty = "$$contentType"

  // NOTE: this should become a system property in future versions of Azure SDKs
  private[iothubreact] val messageTypeProperty = "$$messageType"

  private[iothubreact] val messageIdProperty = AmqpConstants.AMQP_PROPERTY_MESSAGE_ID

  private[iothubreact] val deviceIdProperty = "iothub-connection-device-id"

  // Internal properties set by IoT stoage
  private[this] lazy val systemProps = data.get.getSystemProperties()

  // Meta properties set by the device
  lazy val properties: util.Map[String, String] = data.get.getProperties()

  // Whether this is a keep alive message generated by the stream and not by IoT hub
  val isKeepAlive: Boolean = (partition == None)

  // Message type, the class to use to map the payload
  lazy val messageType: String = properties.getOrDefault(messageTypeProperty, "")

  // Content type, e.g. JSON/Protobuf/Bond etc.
  // contentType = data.get.getSystemProperties.get(contentTypeProperty)
  lazy val contentType = properties.getOrDefault(contentTypeProperty, "")

  // Time when the message was received by IoT hub service. *NOT* the device time.
  lazy val created: Instant = systemProps.getEnqueuedTime

  // IoT message offset, useful to store the current position in the stream
  lazy val offset: String = systemProps.getOffset

  // IoT message sequence number
  lazy val sequenceNumber: Long = systemProps.getSequenceNumber

  // ID of the device who sent the message
  lazy val deviceId: String = systemProps.get(deviceIdProperty).toString

  // Message ID
  lazy val messageId: String = systemProps.get(messageIdProperty).toString

  // IoT message content bytes
  lazy val content: Array[Byte] = data.get.getBody

  // IoT message content as string, e.g. JSON/XML/etc.
  lazy val contentAsString: String = new String(content)
}
