// Copyright (c) Microsoft. All rights reserved.

/*
    SETUP

     CONFIGURE DEVICES IN AZURE IOT HUB

        1. Create an Azure IoT hub, and get the "iothubowner" connection string form the portal
        2. # npm install -g iothub-explorer
        3. # iothub-explorer login "conn string"
        4. # for i in {1000..1010}; do iothub-explorer create device$i --display="deviceId"; done

    EXPORT CREDENTIALS TO 'credentials.js' (in the folder of main.js)

        1. # DATA=$(iothub-explorer list --display="deviceId,authentication.SymmetricKey.primaryKey," --raw|sort|awk '{ print $0 ","}')
        2. # echo "var hubDevices = [$DATA];" > credentials.js

    RUN

        # node main.js

*/

"use strict";

// How frequently to send data
var frequency = 1000;

// Name of your Azure IoT hub (if truncated, use the value from the connection string)
var hubName = "my-iothub";

// Available protocols
//var Protocol = require("azure-iot-device-amqp-ws").AmqpWs;
//var Protocol = require("azure-iot-device-amqp").Amqp;
var Protocol = require("azure-iot-device-http").Http;

// Load credentials
require("vm").runInThisContext(require("fs").readFileSync(__dirname + "/credentials.js"))

// Instantiate simulators
var TemperatureSimulator = require("./temperature_simulator.js");
var HumiditySimulator = require("./humidity_simulator.js");

// Connect simulators to Azure IoT hub
var devices = [];
var j = 0;
for (var i = 0; i < hubDevices.length ; i++) {
  var deviceId = hubDevices[i][0].deviceId;
  var accessKey = hubDevices[i][0].authentication.SymmetricKey.primaryKey;

  devices[j] = new TemperatureSimulator(hubName, deviceId, accessKey, Protocol, frequency);
  devices[j++].connect();
  devices[j] = new HumiditySimulator(hubName, deviceId, accessKey, Protocol, frequency);
  devices[j++].connect();
}

// Start sending data generated by the simulators
for (var i = 0; i < devices.length ; i++) {
  devices[i].startSending();
}
