// Copyright (c) Microsoft. All rights reserved.

/*
    SETUP

    CONFIGURE DEVICES IN AZURE IOT HUB

        1. Create an Azure IoT hub, then get the "iothubowner" connection string

        2. Download iothub-explorer.js from

            https://github.com/Azure/azure-iot-sdks/tree/master/tools/iothub-explorer

        3. # npm install
        4. # iothub-explorer.js login "conn string"
        5. # for i in {1000..1010}; do node iothub-explorer.js create device$i --display="deviceId"; done

    EXPORT CREDENTIALS TO 'credentials.js'

        1. # DATA=$(node iothub-explorer.js list --display="deviceId,authentication.SymmetricKey.primaryKey," --raw|sort|awk '{ print $0 ","}')
        2. # echo "var hubDevices = [$DATA];" > credentials.js
        4. Move the `credentials.js` file in thes same folder of this `main.js` file

    RUN

        # node main.js

*/

"use strict";

// How frequently to send data
var frequency = 1000;

// Name of your Azure IoT hub (if truncated, use the value from the connection string)
var hubName = "my-iothub";

// Available protocols
//var Protocol = require("azure-iot-device-amqp-ws").AmqpWs;
//var Protocol = require("azure-iot-device-amqp").Amqp;
var Protocol = require("azure-iot-device-http").Http;

// Load credentials
require("vm").runInThisContext(require("fs").readFileSync(__dirname + "/credentials.js"))

// Instantiate simulators
var TemperatureSimulator = require("./temperature_simulator.js");
var HumiditySimulator = require("./humidity_simulator.js");

// Connect simulators to Azure IoT hub
var devices = [];
var j = 0;
for (var i = 0; i < hubDevices.length ; i++) {
  var deviceId = hubDevices[i][0].deviceId;
  var accessKey = hubDevices[i][0].authentication.SymmetricKey.primaryKey;

  devices[j] = new TemperatureSimulator(hubName, deviceId, accessKey, Protocol, frequency);
  devices[j++].connect();
  devices[j] = new HumiditySimulator(hubName, deviceId, accessKey, Protocol, frequency);
  devices[j++].connect();
}

// Start sending data generated by the simulators
for (var i = 0; i < devices.length ; i++) {
  devices[i].startSending();
}
